import assert from "node:assert/strict";
import test from "node:test";
import { skillCompatProblems } from "./skill-compat-lib.mjs";

const cases = [
  ["valid plain", "name: meta-mode\ndescription: Route a task through a workflow.", 0],
  ["valid plain with colon inside a word", "name: a\ndescription: See http://example.com/x or a:b", 0],
  ["valid double-quoted", 'name: tdd\ndescription: "Use when: a bug has a test, # not a comment"', 0],
  ["valid single-quoted", "name: tdd\ndescription: 'Use when: a bug'", 0],
  ["valid block scalar", "name: tdd\ndescription: >\n  Use when: a bug", 0],
  ["valid literal block", "name: tdd\ndescription: |-\n  Use when: a bug", 0],
  ["valid multiline plain string", "name: tdd\ndescription: Use for bugs\n  when a test fails\n  or a regression appears", 0],
  ["valid multiline plain string starting on the next line", "name: tdd\ndescription:\n  Use for bugs\n  when a test fails", 0],
  ["valid multiline plain string with CRLF", "name: tdd\r\ndescription: Use for bugs\r\n  when a test fails\r\n", 0],
  ["valid hyphen, question mark and colon without a separator", "name: tdd\ndescription: -fast ?maybe :colon a-b", 0],
  ["valid NBSP after a colon", "name: tdd\ndescription: Use when: a bug", 0],
  ["valid NBSP before a hash", "name: tdd\ndescription: Use for bugs #urgent", 0],
  ["valid ideographic space around a colon and hash", "name: tdd\ndescription: Use when:　a bug 　#x", 0],
  ["valid next field after a multiline value", "name: tdd\ndescription: Use for bugs\n  when a test fails\nmetadata:\n  a: b", 0],
  ["valid quoted colon", 'name: tdd\ndescription: "a: b"', 0],
  ["valid single-quoted escape", "name: tdd\ndescription: 'it''s'", 0],
  ["valid escaped double quote", 'name: tdd\ndescription: "say \\"hi\\": now"', 0],
  ["valid quoted with trailing comment", 'name: tdd\ndescription: "a b" # note', 0],
  ["valid quoted continuing onto indented lines", 'name: tdd\ndescription: "Use for bugs\n  when: a test fails"', 0],
  ["valid chomp-only block header", "name: tdd\ndescription: >-\n  Use when: a bug", 0],
  ["valid indent-only block header", "name: tdd\ndescription: |2\n  Use when: a bug", 0],
  ["valid indent and chomp block header", "name: tdd\ndescription: >2+\n  Use when: a bug", 0],
  ["valid block header with a comment", "name: tdd\ndescription: > # folded\n  Use when: a bug", 0],
  ["valid quoted name with a trailing comment", 'name: "tdd" # skill\ndescription: ok', 0],
  ["valid escaped quote", 'name: tdd\ndescription: "say \\"hi\\""', 0],
  ["valid escaped backslash", 'name: tdd\ndescription: "C:\\\\skills"', 0],
  ["valid unicode escape", 'name: tdd\ndescription: "caf\\u00e9"', 0],
  ["valid hex and long unicode escapes", 'name: tdd\ndescription: "\\x41 \\U0001F600 \\N\\_\\L\\P\\0\\a\\b\\t\\n\\v\\f\\r\\e\\/ \\ "', 0],
  ["valid escaped line continuation", 'name: tdd\ndescription: "Use for \\\n  bugs"', 0],
  ["invalid escape C:\\skills", 'name: tdd\ndescription: "Use files under C:\\skills"', 1, /invalid escape \\s/],
  ["short hex escape", 'name: tdd\ndescription: "a\\x4"', 1, /invalid escape \\x \(needs 2 hex digits\)/],
  ["non-hex digits in hex escape", 'name: tdd\ndescription: "a\\x4g"', 1, /invalid escape \\x/],
  ["short unicode escape", 'name: tdd\ndescription: "a\\u12"', 1, /invalid escape \\u \(needs 4 hex digits\)/],
  ["short long-unicode escape", 'name: tdd\ndescription: "a\\U0001F60"', 1, /invalid escape \\U \(needs 8 hex digits\)/],
  ["backslash at the end of the value", 'name: tdd\ndescription: "abc\\', 1, /unterminated double-quoted/],
  ["backslash is literal in single quotes", "name: tdd\ndescription: 'C:\\skills'", 0],
  ["valid block body", "name: tdd\ndescription: >-\n  Use when a bug\n  needs a test", 0],
  ["valid block body with CRLF", "name: tdd\r\ndescription: >-\r\n  Use when a bug\r\n  needs a test\r\nmetadata:\r\n  a: b", 0],
  ["valid explicit indent with deeper body", "name: tdd\ndescription: >2\n    Use when a bug\n  needs a test", 0],
  ["valid blank line inside a block body", "name: tdd\ndescription: |\n  Use when a bug\n\n  needs a test", 0],
  ["block explicit indent with a 1-space line", "name: tdd\ndescription: >2\n  Use when a bug\n needs a test", 1, /indented less than 2 space/],
  ["block explicit indent with a 1-space line and CRLF", "name: tdd\r\ndescription: >2\r\n needs a test\r\n", 1, /indented less than 2 space/],
  ["block body less indented than its first line", "name: tdd\ndescription: >\n    Use when a bug\n  needs a test", 1, /indented less than 4 space/],
  ["block with an empty body", "name: tdd\ndescription: >-\nmetadata:\n  a: b", 1, /empty block scalar body/],
  ["block with an empty body at the end", "name: tdd\ndescription: |", 1, /empty block scalar body/],
  ["block with an empty body and CRLF", "name: tdd\r\ndescription: >-\r\nmetadata:\r\n  a: b\r\n", 1, /empty block scalar body/],
  ["tab-indented block body", "name: tdd\ndescription: >\n\tUse when a bug", 1, /indented less than 1 space/],
  ["header on the next line with trailing text", "name: tdd\ndescription:\n  | Use when a bug", 1, /invalid block scalar header/],
  ["dedented comment after a block body", "name: tdd\ndescription: |-\n  Use when a bug needs a test.\n # Keep metadata separate.\nmetadata:\n  category: testing", 0],
  ["dedented comment after a block body with CRLF", "name: tdd\r\ndescription: |-\r\n  Use when a bug needs a test.\r\n # Keep metadata separate.\r\nmetadata:\r\n  category: testing\r\n", 0],
  ["several dedented comments after a block body", "name: tdd\ndescription: >\n   Use when a bug.\n  # one\n # two\n    # three", 0],
  ["comment as deep as the body is body text", "name: tdd\ndescription: |\n  Use when a bug.\n  # literal text\n", 0],
  ["dedented non-comment after a block body", "name: tdd\ndescription: |-\n  Use when a bug needs a test.\n Keep metadata separate.\nmetadata:\n  category: testing", 1, /indented less than 2 space/],
  ["dedented non-comment after a block body with CRLF", "name: tdd\r\ndescription: |-\r\n  Use when a bug needs a test.\r\n Keep metadata separate.\r\nmetadata:\r\n  category: testing\r\n", 1, /indented less than 2 space/],
  ["non-comment after a dedented comment", "name: tdd\ndescription: |\n  Use when a bug.\n # note\n  more text", 1, /indented less than 2 space/],
  ["comment dedented below an explicit indent as the first line", "name: tdd\ndescription: >2\n # note\n  body", 1, /indented less than 2 space/],
  ["comment lines between the key and a next-line header", "name: tdd\ndescription:\n  # note\n  >-\n    Use when a bug", 0],
  ["comment lines between the key and a next-line plain value", "name: tdd\ndescription: # note\n  # more\n  Use for bugs", 0],
  ["only comment lines after the key", "name: tdd\ndescription:\n  # note\nmetadata:\n  a: b", 1, /description is empty or comment-only/],
  ["valid header on the next line", "name: tdd\ndescription:\n  >-\n    Use when a bug has a cheap regression test.", 0],
  ["valid header on the next line with CRLF", "name: tdd\r\ndescription:\r\n  >-\r\n    Use when a bug has a cheap regression test.\r\nmetadata:\r\n  a: b\r\n", 0],
  ["valid header on the next line with a same-indent body", "name: tdd\ndescription:\n  |\n  Use when: a bug", 0],
  ["valid header on the next line after a comment", "name: tdd\ndescription: # note\n  >2\n      Use when: a bug", 0],
  ["header on the next line with a zero-indented body", "name: tdd\ndescription:\n  >-\nUse when a bug", 1, /empty block scalar body/],
  ["header on the next line with a zero-indented body and CRLF", "name: tdd\r\ndescription:\r\n  >-\r\nUse when a bug\r\n", 1, /empty block scalar body/],
  ["header on the next line with a shallow explicit indent", "name: tdd\ndescription:\n  >2\n Use when a bug", 1, /indented less than 2 space/],
  ["valid next-line quoted scalar", 'name: tdd\ndescription:\n  "Use when: a bug"', 0],
  ["malformed next-line quoted scalar", 'name: tdd\ndescription:\n  "Use when: a bug', 1, /unterminated double-quoted/],
  ["block indicator inside a plain multiline scalar", "name: tdd\ndescription: Use for bugs\n  > when a test fails", 0],
  ["comment-only description", "name: tdd\ndescription: # comment", 1, /description is empty or comment-only/],
  ["comment without a space", "name: tdd\ndescription: #x", 1, /description is empty or comment-only/],
  ["empty description", "name: tdd\ndescription:\nmetadata:\n  a: b", 1, /description is empty or comment-only/],
  ["comment-only name", "name: # skill\ndescription: ok", 1, /name is empty or comment-only/],
  ["comment after the key then a value", "name: tdd\ndescription: # note\n  Use for bugs", 0],
  ["unterminated double quote", 'name: tdd\ndescription: "unterminated', 1, /unterminated double-quoted/],
  ["unterminated single quote", "name: tdd\ndescription: 'unterminated", 1, /unterminated single-quoted/],
  ["escaped closing double quote", 'name: tdd\ndescription: "abc\\"', 1, /unterminated double-quoted/],
  ["unescaped apostrophe in single quotes", "name: tdd\ndescription: 'it's'", 1, /content after the closing '/],
  ["content after a closing double quote", 'name: tdd\ndescription: "a" b', 1, /content after the closing "/],
  ["hash glued to a closing quote", 'name: tdd\ndescription: "a"#b', 1, /content after the closing "/],
  ["content on a later line after a closing quote", 'name: tdd\ndescription: "a"\n  b', 1, /content after the closing "/],
  ["quoted name unterminated", 'name: "tdd\ndescription: ok', 1, /name has an unterminated/],
  ["block header with trailing text", "name: tdd\ndescription: |oops\n  body", 1, /invalid block scalar header \|oops/],
  ["block header with two indent digits", "name: tdd\ndescription: >12\n  body", 1, /invalid block scalar header/],
  ["block header with zero indent", "name: tdd\ndescription: |0\n  body", 1, /invalid block scalar header/],
  ["hash comment message", "name: tdd\ndescription: Use for bugs #urgent", 1, /starts a YAML comment and truncates the value; quote the value/],
  ["indented hash line message", "name: tdd\ndescription: Use for bugs\n  # note", 1, /starts a YAML comment and truncates the value; quote the value/],
  ["nested mapping as description", "name: tdd\ndescription:\n  Use when: a bug", 1, /description contains ': '/],
  ["sequence as description", "name: tdd\ndescription:\n  - Run tests", 1, /starts with YAML indicator -/],
  ["leading hyphen separator", "name: tdd\ndescription: - Run tests", 1, /starts with YAML indicator -/],
  ["leading hyphen separator with CRLF", "name: tdd\r\ndescription: - Run tests\r\n", 1, /starts with YAML indicator -/],
  ["leading hyphen separator with a tab", "name: tdd\ndescription: -\tRun tests", 1, /starts with YAML indicator -/],
  ["leading question mark separator", "name: tdd\ndescription: ? Run tests", 1, /starts with YAML indicator \?/],
  ["leading colon separator", "name: tdd\ndescription: : Run tests", 1, /starts with YAML indicator :/],
  ["lone leading hyphen", "name: tdd\ndescription: -", 1, /starts with YAML indicator -/],
  ["leading flow closer", "name: tdd\ndescription: ] Run tests", 1, /starts with YAML indicator \]/],
  ["colon continuation line", "name: tdd\ndescription: Use for bugs\n  Use when: a test fails", 1, /description contains ': '/],
  ["colon continuation line with CRLF", "name: tdd\r\ndescription: Use for bugs\r\n  Use when: a test fails\r\n", 1, /description contains ': '/],
  ["trailing colon on a continuation line", "name: tdd\ndescription: Use for bugs\n  Use when:\n  a test fails", 1, /description contains ': '/],
  ["hash continuation line", "name: tdd\ndescription: Use for bugs\n  when a test fails #urgent", 1, /description contains ' #'/],
  ["comment-only continuation line", "name: tdd\ndescription: Use for bugs\n  # note\n  when a test fails", 1, /description contains ' #'/],
  ["tab separator before a hash", "name: tdd\ndescription: Use for bugs\t#urgent", 1, /description contains ' #'/],
  ["tab separator after a colon", "name: tdd\ndescription: Use when:\ta bug", 1, /description contains ': '/],
  ["plain with ': '", "name: tdd\ndescription: Use when: a bug", 1, /description contains ': '/],
  ["plain with trailing colon", "name: tdd\ndescription: Use for bugs:", 1, /description contains ': '/],
  ["plain with ' #'", "name: tdd\ndescription: Use for bugs #urgent", 1, /description contains ' #'/],
  ["plain with leading bracket", "name: tdd\ndescription: [draft] Use for bugs", 1, /starts with YAML indicator \[/],
  ["plain with leading backtick", "name: tdd\ndescription: `tdd` helper", 1, /starts with YAML indicator `/],
  ["plain with leading star", "name: tdd\ndescription: *important* bugs", 1, /starts with YAML indicator \*/],
  ["plain name with ': '", "name: a: b\ndescription: ok", 2, /name contains ': '/],
  ["name with space", "name: my skill\ndescription: ok", 1, /name my skill does not match/],
  ["name with dot", "name: my.skill\ndescription: ok", 1, /does not match/],
  ["name starting with hyphen", "name: -skill\ndescription: ok", 1, /does not match/],
  ["name without a letter", "name: 123\ndescription: ok", 1, /does not match/],
  ["quoted name that violates the pattern", 'name: "my skill"\ndescription: ok', 1, /does not match/],
  ["valid name with colon and underscore", "name: plugin:my_skill-2\ndescription: ok", 0],
];

for (const [label, frontmatter, count, pattern] of cases) {
  test(`skill compat: ${label}`, () => {
    const problems = skillCompatProblems(frontmatter);
    assert.equal(problems.length, count, problems.join("\n"));
    if (pattern) assert.match(problems.join("\n"), pattern);
  });
}
